### PR TITLE
Added information to production rate related notebooks

### PR DESCRIPTION
**Pull request by gianninapr**
Added pyradex example

### CODE REVIEW

**Comment by mkelley** [comment]
I didn't read it in detail, but have just a few simple recommended edits.  This is OK as a single notebook, but I recommend, either now or in the future, to split it up into individual tasks with helpful file names.  That will help users discover the functionality they are most interested in.

I'm not sure the best way to comment on notebooks, so I'll just copy paste here:

> One of these models is based on the following paper: ...

"An LTE model based on [Drahus et al. (2012)](https://ui.adsabs.harvard.edu/abs/2012ApJ...756...80D/abstract) is implemented.  The model does not ..."

The citations in the Haser section should also be similarly written and use the NASA ADS pages:

https://ui.adsabs.harvard.edu/abs/1957BSRSL..43..740H/abstract
https://ui.adsabs.harvard.edu/abs/2018AJ....156...34W/abstract

And again in the from_pyradex section.

> The calculations below are based and compared against results published in Drahus et al. 2012.

"... Drahus et al. (2012)."

> from the literature (Drahus et al. 2012)

is unnecessarily repeated in "LTE from_Drahus First Example" and "LTE from_Drahus Second Example (User-defined Data)"

**Comment by gianninapr** [comment]
@mkelley do you have any suggestions in terms of splitting it up? I was thinking probably splitting between LTE and NonLTE methods but that wouldn't really change much.

**Comment by mkelley** [comment]
It looks like three notebooks to me: LTE without photo-dissociation, LTE with Haser, and Non-LTE with Pyradex.

**Comment by gianninapr** [comment]
@mkelley got it!

**Pull request merged**
